Update shared.yaml

diff --git a/.github/workflows/shared.yaml b/.github/workflows/shared.yaml
--- a/.github/workflows/shared.yaml
+++ b/.github/workflows/shared.yaml
@@ -19,3 +19,7 @@ jobs:
         run: |
           aaa=$((${{ inputs.count }}))
           echo $aaa
+          if [ "${{ inputs.count }}" != "0" -a $aaa -eq 0 ]; then
+            echo "Error: invalid input"
+            exit 1
+          fi
